name = "hyperlane/cardano"
version = "0.1.0"
license = "Apache-2.0"
description = "Hyperlane cross-chain messaging protocol for Cardano"

[repository]
user = "hyperlane"
project = "cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"
